- name: selrescuing
  block:
  - name: copy
    ansible.builtin.copy:
      src: '{{playbook_dir}}/ehi.txt'
      dest: '{{playbook_dir}}/ehl.txt'
  rescue:
  - name: copy
    ansible.builtin.include_tasks:
      file: copy.yaml

